# Generated by Django 5.0.6 on 2024-07-01 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('desktop', 'Desktop Development'), ('game', 'Game Development'), ('other', 'Other Development')], max_length=100)),
            ],
        ),
    ]
